# Generated by Django 3.2.9 on 2021-11-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adminnote',
            field=models.CharField(blank=True, max_length=222),
        ),
        migrations.AddField(
            model_name='order',
            name='ip',
            field=models.CharField(blank=True, max_length=222),
        ),
    ]
