# Generated by Django 3.2.9 on 2021-11-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0005_auto_20211118_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='title',
        ),
    ]
