# Generated by Django 3.2.9 on 2021-11-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
        migrations.RenameField(
            model_name='license',
            old_name='images',
            new_name='image',
        ),
    ]
