# Generated by Django 3.2.9 on 2021-11-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_category_comment_images_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='stu',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='word',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
